### ISSUE TITLE
what's the deal with `libmapper-0.so` (vs `libmapper.so`)

### ISSUE THREAD

**Issue by umlaeute** [libmapper/libmapper#19]
Why is the generated library name `libmapper-<MAJOR_VERSION>.so`??
imho, the library should be named `libmapper.so` (and [semantic versioning](http://semver.org/) should be in action)

### in-project inconsistency
in [`src/Makefile.am`](https://github.com/libmapper/libmapper/blob/master/src/Makefile.am#L9) the actual library-name is set as `libmapper-@MAJOR_VERSION@.la`
the `@MAJOR_VERSION@` is calculated dynamically from the `PACKAGE_VERSION` at configure time (though this is broken for releases, see #18).
On the other hand, the [python bindings](https://github.com/libmapper/libmapper/blob/master/swig/setup.py.in#L22) **hardcode** the library-name to be `libmapper-0` (ignoring any calculated `MAJOR_VERSION`)

### inconsistency regarding the rest of the world
Libraries are usually named `libfoo.so`, not `libfoo-X.so`.
If you want semantic versioning (which you should), then the canonical way is to have the actual libraryname be `libfoo.so.X.Y.Z`.
There is no compelling reason to include the package version in the library name (ABI breakage is captured by semver).

An obvious indicator for this is the clumsiness required to get this behaviour into [`src/Makefile.am`](https://github.com/libmapper/libmapper/blob/master/src/Makefile.am), which is now littered by barely readable @@-expansions. Since automakefiles are really supposed to make *best practices* as simple possible, the extra code required is a good indicator that you are doing something wrong (though admittedly, autotools sometimes makes it hard to draw the distinction)

**Comment by radarsat1** [comment]
The software, until considered stable, is not named "libmapper", but "libmapper-0".  We left the -0 in the name until we have some kind of agreement that the API, ABI and protocol are considered stable.  So yes, it's an indicator that it should be used experimentally.  It could be time to have that discussion, but since there's exactly 1 person maintaining libmapper right now, fixing this should be left up to @malloch.  Also please keep in mind that it's rather helpful on Windows to have the binary named libmapper-0.dll.

I'll note that although it's not used here for the stated purpose, putting a version number in the library name is entirely acceptable as per the [libtool manual](https://autotools.io/libtool/version.html)

In any case, I'm all for removing the -0 at this point, depending on what @malloch thinks.
There was quite a bit of thoughts and re-organizing going on until recently, which resulted in a loss of confidence to the forward-compatibility of the API, but I'm not sure of the current situation.

**Comment by radarsat1** [comment]
Hm, i wish i could move this issue over to the libmapper/libmapper project..

**Comment by radarsat1** [comment]
I'll note that it appears that my -0 version number totally worked the way I wanted, since the whole point was to stop people building distro packages before the software was considered stable :P  Thanks for taking an interest!  It's been enough time that we've been "unstable" that it's clearly time to have this discussion.

**Comment by umlaeute** [comment]
indeed :-)

### playing the devil's advocate...

however, the official homepage links to the github repo for current development, which has its last commit 2 years ago.
if you consider such software still *unstable* and not for public consumption, then i would rather label it abandonware (and have it removed from Debian).

**Comment by radarsat1** [comment]
It's already in Debian?

**Comment by radarsat1** [comment]
For the record @malloch still works on it regularly.

**Comment by radarsat1** [comment]
I think most of his work is on branches that haven't been merged.

**Comment by umlaeute** [comment]
### regarding updates
yes i thought so; i guess he forgot to push to github though

### regarding Debian:
it has been in Debian/unstable for a while https://tracker.debian.org/pkg/libmapper (not my doing).
i recently went through some of the multimedia related packages to see which ones will not make it into `Debian/stretch` (to be released in spring 2017), and `libmapper` was among them, so i started to update it.
the package is (currently) not scheduled from `Debian/stretch` [on purpose](https://bugs.debian.org/768901)

**Comment by radarsat1** [comment]
ok, cool, thanks for the info regarding Debian.  It's really useful to know what's going on with the packages!  Probably I'll have some time to pay attention to libmapper in the next weeks and @malloch and I can have some discussions regarding merging some stuff, and doing a point release targeted towards protocol stability.  I'll leave this open until then so that you're in the loop.

**Comment by umlaeute** [comment]
thanks.

one small issue though (and please don't let that stress you): the time window to get things into the *next* Debian release is closing pretty soon. anything that is not in `Debian/testing` by 2015-01-05, will not be in the release (and it takes at least 10 days to migrate from *Debian/unstable* to *Debian/testing*; and since there are a few disruptive changes in the packaging, it will take more than 10 days)

**Comment by tiagovaz** [comment]
On Mon, Dec 12, 2016 at 11:57:29AM -0800, Stephen Sinclair wrote:
> ok, cool, thanks for the info regarding Debian.  It's really useful to know what's going on with the packages!  Probably I'll have some time to pay attention to libmapper in the next weeks and @malloch and I can have some discussions regarding merging some stuff, and doing a point release targeted towards protocol stability.  I'll leave this open until then so that you're in the loop.

You can ping me if you need any help with the packages. It's in the same
shape since it was uploaded in 2014, Debian unstable only. At that time
I was told to avoid releasing packages before having a stable release
from upstream. I stopped following and have no idea if a stable release
is out there or not.

-- 
tiago

**Comment by radarsat1** [comment]
I guess an explanation is warranted.. the story is that libmapper has always been a concrete implementation of ideas that came up during @malloch and my doctoral studies. We were constantly discussing it and changing things and playing around, but since it was a protocol we didn't want to announce anything as "stable" and risk breaking stuff for people or alternatively getting stuck with old features.  In other words even though we honestly thought it was a useful approach to mapping and IO, we weren't ready for anyone to use it that we didn't "know", not just because of bugs, but due to uncertainty regarding the idea itself.

These days however there are some users in a couple of universities that we know of, and @malloch actively uses it for a few projects as well as students in the IDMIL https://github.com/idmil so, although it remains a playground, I think it's seen rather fewer changes in the last 3 or 4 years since we both graduated.  So it's probably a very good time to be thinking about stabilising a large subset of the protocol and API at this point, and it would be cool to see people building tools on top of it.  So I'm game.  None of us has a ton of time for maintenance, is the only issue I think, but I'll probably be willing to keep it at least building correctly for the foreseeable future.

**Comment by radarsat1** [comment]
Closed in 1a49608.
