### ISSUE TITLE
Libmapper Startup Delay

### ISSUE THREAD

**Issue by fundamental** [libmapper/libmapper#4]
Currently Libmapper has a 2 second delay from creating a device with _mdev_new()_ to when _mdev_ready()_ will return true.
Based upon my reading of the source code, libmapper will not inform the admin channel that it has a port until this two second period has passed and it will perform this operation within a call to _mdev_poll()_. If libmapper is operating on data structures owned by a realtime thread, then it would make sense that the only location _mdev_poll()_ should be called is the realtime (eg jack audio) thread. For this to be safe from blocking functions, the libmapper device must be ready.

So, for an application using libmapper for the above manner, there must be a 2 second delay at startup. This timing is due to _admin.c:check_collisions()_.

I personally get annoying waiting 2+ seconds for a trivial program to start, waiting for libmapper to lock its resources, so:
A) Could this 2 second libmapper collision detection scheme be transitioned to some temporary thread?
B) Could this time be reduced significantly?

**Comment by radarsat1** [comment]
Hi, good comment.  The start-up time is needed to resolve any collisions with other devices on the network or same computer, e.g. to ensure the same name is not used.  Technically it is not needed for the port; I tried removing it once instead depending on detecting used ports by whether bind() succeeded, but I forget exactly why, but it caused some issues so I left it.  That could probably be investigated more thoroughly.

Apart from that, though, I can't think of an alternative in a P2P system for detecting name collisions, other than a system where it announces the intended name, and waits a certain amount of time for other devices to contest that choice.

However, two things:

1) You do not need to explicitly wait for mdev_ready() to start your program doing useful things.  You can ignore calling mdev_ready() at all, it is only useful for checking whether the device name is known e.g. for displaying it on the screen.  The timeout must expire of course before the device starts accepting connections, but your program logic can ignore that.  Just call mdev_new() and then go ahead right into your mdev_poll() loop, that is the intended sequence.

It can indeed be annoying to wait 2 seconds to start accepting connections, of course, but libmapper is not really meant to be used with programs that start and stop often.  Of course it can be an annoyance during development; I don't have a solution for this.

2) By the way, mdev_poll() is not, at this time, real-time safe.  It can be called from an audio thread, and I do this myself, but keep in mind that there are plenty of mallocs and frees that can occur inside mdev_poll(), even if it is used non-blocking.  If you want to be careful and correct, you can put it on its own thread and transmit data from your callbacks to your audio thread using a ring buffer.  I have some ideas for adding an API "real-time layer" for supporting this kind of thing sometime, but it's not currently on the priority list.

**Comment by fundamental** [comment]
> Of course it can be an annoyance during development

It might be possible to create a 'mdev_you_are_a_bad_person_for_calling_this()' function to make development easier by skipping the 2 second period.

>  By the way, mdev_poll() is not, at this time, real-time safe.

Well, darn. I had assumed that mdev_poll() was realtime safe when non-blocking and after the initial setup of the callbacks. Is liblo at least safe with its nonblocking api? How much tweaking would be required to make it possible for a very basic "real-time layer"? If it is not too much, I might be able to spend some time working on this issue.

The main reason why I ask, is that I am guilty of working with a lot of real-time unsafe code and I want any future program I make to be safe. Libmapper provides a very useful api for specifying update functions without neededing users to reinvent the wheel in terms of sending messages over a ringbuffer and defining format, but no real-time support is a dealbreaker for most of the applications I currently have in mind. (xruns have become the bane of my software work). Lastly while it would be possible to use a ringbuffer, that by in large defeats the utility of libmapper (as a developer).

**Comment by radarsat1** [comment]
> >  By the way, mdev_poll() is not, at this time, real-time safe.
> 
> Well, darn. I had assumed that mdev_poll() was realtime safe when non-blocking and after the initial setup of the callbacks. Is liblo at least safe with its nonblocking api? How much tweaking would be required to make it possible for a very basic "real-time layer"? If it is not too much, I might be able to spend some time working on this issue.

Unfortunately many libraries are not real-time safe.  I also tend to
ignore this often, but the fact is that if there is memory allocation
going on, the code is not real-time safe.  During mdev_poll(), the
library can accept new links and connections, meaning allocation of
some data structures.
In general there is no way around being very careful about message
passing when dealing with real-time stuff.

(And the answer is no, liblo is not real-time safe either.  It's a
long-term goal to remove dynamic mallocs, but currently malloc is
called during message retrieval. Try grepping for "malloc" in server.c
-- not that many, but 6 hits are returned, 4 which are involved in
recv functionality.)

Anyways, strictly speaking the protocol can be divided into two: the
admin messages used to manage connections, and the signal messages
used to transmit data.  Given a real-time channel (such as a
non-blocking FIFO), a possibility would be to have mdev_poll() call
standard signal handlers that forward data messages over this channel
to another thread.  This kind of functionality could perhaps be
provided by the library.

Another possibility is to have synthesizer parameters contained in a
single data structure.  The libmapper thread on receiving signal
messages would update a local set of parameters, and atomically swap
the synthesizer's parameter pointer.  This approach would avoid the
need for much data copying, so it might be preferable, but is of
course more difficult to generalize and put into a library, since
parameters are application-specific.

In both approaches, the important point is that the FIFOs or parameter
structs are pre-allocated at the beginning of the program, and the
real-time process should do things like pre-access all memory and lock
memory paging, etc.  There are articles on this topic, often operating
system-specific of course.

> The main reason why I ask, is that I am guilty of working with a lot of real-time unsafe code and I want any future program I make to be safe. Libmapper provides a very useful api for specifying update functions without neededing users to reinvent the wheel in terms of sending messages over a ringbuffer and defining format, but no real-time support is a dealbreaker for most of the applications I currently have in mind. (xruns have become the bane of my software work). Lastly while it would be possible to use a ringbuffer, that by in large defeats the utility of libmapper (as a developer).

I'm glad you find the idea of libmapper useful, and I think it could
eventually provide some real-time safe functionality, but in the
meantime I think there are several approaches that aren't too taxing.
If your number of signals is static, handling a small FIFO for each
signal means adding just a couple of function calls, a "put" in your
signal handler, and a "get" in your real-time thread.  I've used the
following small C++ class on some projects without issue:

https://github.com/radarsat1/dimple/blob/master/src/CircBuffer.h

In any case, even without real-time guarantees, libmapper provides
lots of useful functionality for making and managing connections
between applications.  However, it's still quite a young library, so
there is definitely room for improvement.

**Comment by fundamental** [comment]
> Given a real-time channel (such as a non-blocking FIFO), a possibility would be to have mdev_poll() call standard signal handlers that forward data messages over this channel to another thread. This kind of functionality could perhaps be provided by the library.

This seems to be the functionality that I was originally looking for. It seems like making `lo_message_deserialize()` and portions of `dispatch_method()` safe should be sufficient for this approach to be feasible. In this case, the polling function should be able to pass serialized messages across a FIFO as mentioned. Then some RT poll could dispatch these messages every at the start of every frame. This could also lead into a basic api for polling from FIFOs, which could be useful for translating messages from GUIs that are linked with the RT code. While feasible,  I'm sure that this would still be tricky to get right, as features like coercion and path globs could mess stuff up, but it should be possible to get working. libmapper should not need too many modifications if liblo was enhanced in this manner (AFAIK).

> In general there is no way around being very careful about message passing when dealing with real-time stuff.

This is why I would love for liblo/libmapper to expand some to make this much easier than it currently is. As it stands it is far too easy to do it wrong. Programmers like to be lazy and the lazy solutions tend to be wrong here.

> in the meantime I think there are several approaches that aren't too taxing.

yep, I'll break out jack/ringbuffer.h for the meantime.

> In any case, even without real-time guarantees, libmapper provides lots of useful functionality for making and managing connections between applications. However, it's still quite a young library, so there is definitely room for improvement.

Precisely why this project has grabbed my interest. (and likely sooner or later my time)

**Comment by radarsat1** [comment]
Great, well I'm glad we agree that there is some possibility for continued work on this topic.  I think I'll close this bug since it seems like a discussion more appropriate for the mailing list, whereas I like to think of the bug tracker for very specific issues rather than feature development.

Before wrapping up though, on the original topic of the start-up delay, there is one issue that might be causing you problems: I found that if liblo is compiled with the flag "--enable-ipv6", it calls a function that sometimes incurs some significant delay during server start-up.  (I think it's getaddrinfo if I remember correctly.)  So if you have used that flag, try compiling liblo without IPv4 support, and maybe it will reduce your start-up time.
