### ISSUE TITLE
INT32/INT64 ranges incorrect

### ISSUE THREAD

**Issue by bboettcher3** [libmapper/libmapper#76]
In a project I'm working on I noticed that some INT32 signals were being initialized with a 64 bit range, which led its maximum value to be b'0011 1111 1000 0000 0000 0000 0000 0000 (aka 1065353216), instead of b'1000 0000 0000 0000 0000 0000 (aka 1). I tried to track down where this might be happening and found the below block (look at line 175) that:
1. forgets the MPR_INT64 type
and
2. casts the min and max to platform-dependent bit lengths using `int`

I assume (2) is why my max is being cast to a 64 bit int, but also (1) should be addressed unless I missed something.

https://github.com/libmapper/libmapper/blob/316343ac8221984d03409148751bdcb1a5c3dbec/src/signal.c#L163-L178

**Comment by bboettcher3** [comment]
After making the changes, the range is still the same value, so maybe it's a webmapper issue. Looking into it..

**Comment by DocSunset** [comment]
I think the missing MPR_INT64 case might be because signals don't use this type... yes, I see in the definition of mpr_sig_new:
https://github.com/libmapper/libmapper/blob/316343ac8221984d03409148751bdcb1a5c3dbec/src/signal.c#L49
And mpr_type_get_is_num in turn:
https://github.com/libmapper/libmapper/blob/316343ac8221984d03409148751bdcb1a5c3dbec/src/mapper_internal.h#L714-L723
So that explains that. So I guess the section you identified might not be the culprit?

**Comment by bboettcher3** [comment]
@DocSunset good catch! So far I've verified using testLinear.c that the given INT32 range is correct in webmapper. I also see that the incorrect value is present when printing the signal properties in the python server. Time to go bitwise!
