### ISSUE TITLE
Pip install python module not possible on mac m1 

### ISSUE THREAD

**Issue by Maxw3llGM** [libmapper/libmapper#84]
I wasn't able to pip install libmapper's python module on the M1 mac for use in say WebMapper,

A work around that I did was too manually link the python modules from the libmapper bindings directory into python PATH.

Also as a warning, when compiling the mac binaries py2app won't work unless it's the most recent version (28.xx). Maybe that's something to include in the documentation.

**Comment by kaseypocius** [comment]
just adding that on my machine this still fails under pip, but works fine on m1 with pip3 - same with the compile instructions for webmapper. Would changing the docs from python to python3 break anything?

**Comment by bboettcher3** [comment]
Okay, did some looking into this today with @Maxw3llGM on his machine:

1. The [instructions for compiling for M1](https://github.com/libmapper/libmapper/blob/main/doc/Cross-compiling%20for%20Apple%20Silicon.md) work perfectly on Max's machine
2. The python wheel works when built on Max's machine, the problem lies in CI to successfully build the dylib and generate the wheel
    - [this](https://github.com/libmapper/libmapper/blob/main/.github/workflows/ci.yml#L74) CI task seems to fail in Actions, but assuming it fully builds, [this](https://github.com/libmapper/libmapper/blob/main/.github/workflows/ci.yml#L118) line only creates the python wheel for the x86 dylib

**Comment by malloch** [comment]
The current version (2.4.2) at https://pypi.org/project/libmapper/ now includes a 'universal' wheel for macOS, so `pip install libmapper` should work on M1.

**Comment by bboettcher3** [comment]
confirmed working on m2 macbook :)
